[package]
name = "threefish_encrypt"
version = "0.1.0"
edition = "2021"

[dependencies]
threefish = "0.5"
cipher = "0.4"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
rand = "0.8"
cmac = "0.7"
crypto-mac = "0.11"